src/objects/Application__c.object
<CustomObject>
    <description>Object to record information from an application by a person requesting a clearance. This covers Aged Care, Child Related, Disability , general and vulnerable persons</description>
    <fields>
        <fullName>Aboriginal_or_Torres_Strait_Islander__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the applicant considers themselves to be of Aboriginal or Torres Strait Islander descent.</description>
        <inlineHelpText>Do you considers yourself to be of Aboriginal or Torres Strait Islander descent.</inlineHelpText>
        <label>Aboriginal or Torres Strait Islander</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Set by user selection, then used to automatically set RecordType</description>
        <inlineHelpText>Set by user selection, then used to automatically set RecordType.</inlineHelpText>
        <label>Application Type</label>
        <picklist>
            <picklistValues>
                <fullName>Aged Care Sector Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Related Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Services Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Employment Probity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vulnerable Person Related Employment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to the Contact that the application is on behalf of.</description>
        <inlineHelpText>The Contact that the application is on behalf of.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country_of_Birth__c</fullName>
        <description>Country that the applicant was born in.</description>
        <inlineHelpText>Country that the applicant was born in.</inlineHelpText>
        <label>Country of Birth</label>
        <picklist>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_First_Name__c</fullName>
        <description>Current first name of applicant.</description>
        <inlineHelpText>Current first name of applicant</inlineHelpText>
        <label>Current First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Last_Name__c</fullName>
        <description>Current last name of applicant.</description>
        <inlineHelpText>Current last name of applicant</inlineHelpText>
        <label>Current Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Middle_Names__c</fullName>
        <description>Current middle name or names of applicant.</description>
        <inlineHelpText>Current middle name or names of applicant</inlineHelpText>
        <label>Current Middle Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Postal_Address__c</fullName>
        <description>Current postal address of the applicant.</description>
        <inlineHelpText>Current postal address of the applicant</inlineHelpText>
        <label>Current Postal Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Current_Postal_Postcode__c</fullName>
        <description>Current postcode of the applicant.</description>
        <inlineHelpText>Current postcode of the applicant</inlineHelpText>
        <label>Current Postal Postcode</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Postal_State__c</fullName>
        <description>Current postal address state of the applicant.</description>
        <inlineHelpText>Current postal address state of the applicant</inlineHelpText>
        <label>Current Postal State</label>
        <picklist>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Postal_Suburb__c</fullName>
        <description>Current postal address suburb of the applicant.</description>
        <inlineHelpText>Current postal address suburb of the applicant</inlineHelpText>
        <label>Current Postal Suburb</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Date of birth of the applicant. String to preservce format from web form.</description>
        <inlineHelpText>Date of birth of the applicant.</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <description>Email address of the applicant.</description>
        <inlineHelpText>Email address of the applicant</inlineHelpText>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender of the applicant.</description>
        <inlineHelpText>Gender of the applicant</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Period_of_Residence_From__c</fullName>
        <description>Date the applicant first moved into their current residence.</description>
        <inlineHelpText>Date the applicant first moved into their current residence</inlineHelpText>
        <label>Period of Residence From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period_of_Residence_To__c</fullName>
        <label>Period of Residence To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Territory_of_Birth__c</fullName>
        <label>State/Territory of Birth</label>
        <picklist>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_No__c</fullName>
        <label>Street No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suburb_Town__c</fullName>
        <label>Suburb/Town</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Telephone_H__c</fullName>
        <label>Telephone (H)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Telephone_M__c</fullName>
        <label>Telephone (M)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Telephone_W__c</fullName>
        <label>Telephone (W)</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>Mr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miss</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Town_City_of_Birth__c</fullName>
        <label>Town/City of Birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_No__c</fullName>
        <label>Unit No</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ScreeningApplicationController.cls
global with sharing class ScreeningApplicationController 
{
	private static final String AGED_CARE = 'Aged Care Sector Employment';
	private static final String CHILD_RELATED = 'Child Related Employment';
	private static final String DISABILITY_SERVICES = 'Disability Services Employment';
	private static final String GENERAL_EMPLOYMENT = 'General Employment Probity';
	private static final String VULNERABLE_PERSON = 'Vulnerable Person Related Employment';

	@RemoteAction
	global static List<Application_Declaration_and_Consents__c> getQuestions(String applicationID, String recordTypeName, String applicationTypes)
	{
		List<Application_Declaration_and_Consents__c> questions = new List<Application_Declaration_and_Consents__c>();
		questions = [SELECT 	ID,
									Question_Text__c,
									Response__c,
									Question_Number__c
							FROM	Application_Declaration_and_Consents__c
							WHERE 	Application__c = :applicationID
							ORDER BY Question_Number__c];

		if(questions.isEmpty())
		{
			Integer questionNumber = 0;
			for(Declaration_and_Consent__c dc : getDefaultQuestions(recordTypeName, applicationTypes))
			{
				Application_Declaration_and_Consents__c adc = new Application_Declaration_and_Consents__c();
				adc.Question_Text__c = dc.Text__c;
				adc.Question_Number__c = ++questionNumber;
				questions.add(adc);
			}
		}
		return questions;
	}

	@RemoteAction
	global static void submitApplications(String applicantID)
	{
		List<Previous_Detail__c> previousDetails = new List<Previous_Detail__c>();
		for(Applicant__c applicant : [SELECT 	Id, 
												Name, 
												Contact__c, 
												Title__c, 
												Current_Last_Name__c, 
												Current_First_Name__c, 
												Current_Middle_Names__c, 
												Gender__c, 
												Town_City_of_Birth__c, 
												State_Territory_of_Birth__c, 
												Country_of_Birth__c, 
												Aboriginal_or_Torres_Strait_Islander__c, 
												Unit_No__c, 
												Street_No__c, 
												Street_Name__c, 
												Suburb_Town__c, 
												State__c, 
												Postcode__c, 
												Period_of_Residence_From__c, 
												Period_of_Residence_To__c, 
												Telephone_H__c, 
												Telephone_W__c, 
												Telephone_M__c, 
												Email_Address__c, 
												Current_Postal_Address__c, 
												Current_Postal_Suburb__c, 
												Current_Postal_State__c, 
												Current_Postal_Postcode__c, 
												Application_Type__c, 
												Date_of_Birth__c, 
												B_Documents__c, 
												X100_Point_Score__c, 
												A_Documents__c, 
												C_Documents__c, 
												Document_Score__c, 
												Referring_Organisation__c,
												(SELECT Id, 
														Name, 
														RecordTypeId, 
														Unit_No__c, 
														Street_No__c, 
														Street_Name__c, 
														Suburb__c, 
														State__c, 
														Postcode__c, 
														Period_of_Residence_From__c, 
														Period_of_Residence_To__c, 
														Applicant__c, 
														Country__c, 
														Type__c, 
														First_and_Middle_Names__c, 
														Last_Name__c, 
														Application__c 
												FROM Previous_Details__r)
										FROM 	Applicant__c 
										WHERE 	Id = :applicantID AND 
												Submitted__c = null])
		{			
			for(String applicationType : applicant.Application_Type__c.split(';'))
			{
				Application__c application = new Application__c(Applicant__c = applicant.ID);
												application.Title__c = applicant.Title__c;
												application.Current_Last_Name__c = applicant.Current_Last_Name__c; 
												application.Current_First_Name__c = applicant.Current_First_Name__c; 
												application.Current_Middle_Names__c = applicant.Current_Middle_Names__c;
												application.Gender__c = applicant.Gender__c ;
												application.Town_City_of_Birth__c = applicant.Town_City_of_Birth__c; 
												application.State_Territory_of_Birth__c = applicant.State_Territory_of_Birth__c ;
												application.Country_of_Birth__c = applicant.Country_of_Birth__c;
												application.Aboriginal_or_Torres_Strait_Islander__c = applicant.Aboriginal_or_Torres_Strait_Islander__c;
												application.Unit_No__c = applicant.Unit_No__c;
												application.Street_No__c = applicant.Street_No__c;
												application.Street_Name__c = applicant.Street_Name__c;
												application.Suburb_Town__c = applicant.Suburb_Town__c;
												application.State__c = applicant.State__c;
												application.Postcode__c = applicant.Postcode__c;
												application.Period_of_Residence_From__c = applicant.Period_of_Residence_From__c;
												application.Period_of_Residence_To__c = applicant.Period_of_Residence_To__c;
												application.Telephone_H__c = applicant.Telephone_H__c;
												application.Telephone_W__c = applicant.Telephone_W__c;
												application.Telephone_M__c = applicant.Telephone_M__c;
												application.Email_Address__c = applicant.Email_Address__c;
												application.Current_Postal_Address__c = applicant.Current_Postal_Address__c;
												application.Current_Postal_Suburb__c = applicant.Current_Postal_Suburb__c;
												application.Current_Postal_State__c = applicant.Current_Postal_State__c;
												application.Current_Postal_Postcode__c = applicant.Current_Postal_Postcode__c;
												application.Application_Type__c = applicant.Application_Type__c;
												application.Date_of_Birth__c = applicant.Date_of_Birth__c;
				insert application;	
				for(Previous_Detail__c pd : applicant.Previous_Details__r)	
				{
					Previous_Detail__c newPd = pd.clone(false, true);
					newPd.Applicant__c = null;
					newPd.Application__c = application.ID;
					previousDetails.add(pd);
				}		
			}
			insert previousDetails;
			applicant.Submitted__c = DateTime.now();
			update applicant;
		}
	}

	private static List<Declaration_and_Consent__c> getDefaultQuestions(String recordTypeName, String applicationTypes)
	{
		List<Declaration_and_Consent__c> declarations = new List<Declaration_and_Consent__c>();
		for(String applicationType : applicationTypes.split(';'))
		{
			if(applicationType == AGED_CARE)
			{
				declarations.add([SELECT 	Ordinal_Aged_Care__c,
											Text__c 
									FROM 	Declaration_and_Consent__c
									WHERE 	RecordType.Name = :recordTypeName AND 
											Ordinal_Aged_Care__c != null
									ORDER BY Ordinal_Aged_Care__c]);
			}
			else if(applicationType == CHILD_RELATED)
			{
				declarations.add([SELECT 	Ordinal_Child_Related__c,
											Text__c 
									FROM 	Declaration_and_Consent__c
									WHERE 	RecordType.Name = :recordTypeName AND 
											Ordinal_Child_Related__c != null
									ORDER BY Ordinal_Child_Related__c]);
			}
			else if(applicationType == DISABILITY_SERVICES)
			{
				declarations.add([SELECT 	Ordinal_Disability_Services__c,
											Text__c 
									FROM 	Declaration_and_Consent__c
									WHERE 	RecordType.Name = :recordTypeName AND 
											Ordinal_Disability_Services__c != null
									ORDER BY Ordinal_Disability_Services__c]);
			}
			else if(applicationType == GENERAL_EMPLOYMENT)
			{
				declarations.add([SELECT 	Ordinal_General_Employment__c,
											Text__c 
									FROM 	Declaration_and_Consent__c
									WHERE 	RecordType.Name = :recordTypeName AND 
											Ordinal_General_Employment__c != null
									ORDER BY Ordinal_General_Employment__c]);
			}
			else if(applicationType == VULNERABLE_PERSON)
			{
				declarations.add([SELECT 	Ordinal_Vulnerable_Person__c,
											Text__c 
									FROM 	Declaration_and_Consent__c
									WHERE 	RecordType.Name = :recordTypeName AND 
											Ordinal_Vulnerable_Person__c != null
									ORDER BY Ordinal_Vulnerable_Person__c]);
			}
		}
		return declarations;
	}
}